version: "3"

services:
  app:
    container_name: app
    volumes: 
      - ./:/app
      - /app/node_modules
    ports: 
      - "3000:3000"
    build:
      context: .
    links: 
      - redis
      - database
    environment:
    - REDIS_URL=redis://cache
    depends_on:
      - database
      - redis
  database:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_USER=root
      - MYSQL_USERNAME=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=blog

  redis:
    container_name: cache
    image: redis
    expose:
      - 6379
