version: "3"

services:
  app:
    container_name: app
    volumes: 
      - ./:/app
      - /app/node_modules
    ports: 
      - "3000:3000"
    build:
      context: .
    links: 
      - redis
      - database
    environment:
    - REDIS_URL=redis://cache
    depends_on:
      - database
      - redis
  database:
    container_name: database
    volumes:
      - ./docker/database:/var/lib/mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=blogapp
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  redis:
    container_name: cache
    image: redis
    expose:
      - 6379
