version: "3"

services:
  app:
    container_name: app 
    ports: 
      - "3000:3000"        
    image: node:10.15.2
    build:
      context: .
    volumes:
      - ./:/myapp
      - /myapp/node_modules
    depends_on: 
      - database
  database:
    container_name: database
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: testapp
    ports:
      - "9229:9229"
      - "3308:3306"
  admin:    
    image: adminer    
    ports:     
      - "8080:8080"
